services:
  sat-engine:
    image: ghcr.io/myromeo/sat-tracker:latest
    container_name: sat-global-engine
    restart: unless-stopped
    environment:
      - CELESTRAK_GROUPS=last-30-days,stations,visual,military
      - CACHE_DIR=/data
      - TLE_REFRESH_HOURS=12
    volumes:
      - sat_cache_data:/data
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true

volumes:
  sat_cache_data:
